name: Run unit test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==1.8.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: Run test
        run: poetry run pytest --cov=sudareph --cov-report=xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.10 }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: ubuntu-latest-${{ matrix.python-version }}
          slug: takesei/sudareph
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
